/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//TODO: Implement tests for this library
//package GithubScraper;
//
//import org.junit.Test;
//
//import githubscraper.Main;
//
//import static org.junit.Assert.*;
//
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Main classUnderTest = new Main();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
