/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubscraper;

import githubscraper.core.ScrapeExecutor;
import githubscraper.requestoperation.ContributionCalendar;
import githubscraper.requestoperation.ContributionCount;



public class Main {

    
    public static void main(String[] args) {
    	
    	//Create commit count command object
    	ContributionCount cmtCount = new ContributionCount();
    	
    	//Create calendar count command object
    	ContributionCalendar cntCal = new ContributionCalendar();
    	
    	//Create new executor to execute these commands
    	ScrapeExecutor executor = new ScrapeExecutor("AdnanCigtekin");
    	
    	//Append these commands to execution queue
    	executor.addOperation(cmtCount);
    	executor.addOperation(cntCal);

    	//Execute all commands
    	String res = executor.executeAll();
    	
    	//Display result
    	System.out.println("RESULT:");
    	System.out.println(res);

    }
}
